type Query {
  allCvs: [Cv!]
  getCv(id: String!): Cv
  getCvSkills(id: String!): [Skill!]
  getCvOwner(id: String!): User
}

type Mutation {
  addCv(input: AddCvInput!): Cv
  updateCv(input: UpdateCvInput!): Cv
  deleteCv(id: String!): Boolean
}

enum Role {
  ADMIN
  USER
}

type Cv {
  id: String!
  name: String!
  age: Int!
  job: String!
  ownerId: String!
}

type User {
  id: String!
  name: String!
  email: String!
  role: Role!
}

type Skill {
  id: String!
  designation: String!
}

input AddCvInput {
  name: String!
  age: Int!
  job: String!
  ownerId: String!
  skillIds: [String!]!
}

input UpdateCvInput {
  id: String!
  name: String
  age: Int
  job: String
  ownerId: String
  skillIds: [String!]
}
