type Query {
  allCvs: [Cv!]
  getCv(id: Int!): Cv
  getCvSkills(id: Int!): [Skill!]
  getCvOwner(id: Int!): User
}

enum Role {
  ADMIN
  USER
}
type Mutation {
  createCv(data: CreateCvInput!): Cv!
  updateCv(data: UpdateCvInput!): Cv!
  deleteCv(id: Int!): Cv!
}

type Subscription {
  userCreated: User!
  cvCreated: Cv!
  skillCreated: Skill!
}

type Cv {
  id: Int!
  name: String!
  age: Int!
  job: String!
  ownerId: Int!
  skillsId: [Int!]!
}

type User {
  id: Int!
  name: String!
  email: String!
  role: Role!
}

type Skill {
  id: Int!
  designation: String!
}

input CreateCvInput {
  name: String!
  age: Int!
  job: String!
  ownerId: Int!
  skillIds: [Int!]!
}

input UpdateCvInput {
  id: Int!
  name: String
  age: Int
  job: String
  ownerId: Int
  skillIds: [Int!]
}
type Subscription {
  cvCreated: Cv!
  cvUpdated: Cv!
  cvDeleted: Cv!
}
